[package]
name = "bg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bg-lib = { version = "0.1.0", path = "../lib" }
clap = { version = "4.5.2", features = ["derive"] }
